name: CI
on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set NATS Server Version
        run: echo "NATS_VERSION=v2.10.9" >> $GITHUB_ENV

      - name: Get nats-server
        run: |
          wget "https://github.com/nats-io/nats-server/releases/download/$NATS_VERSION/nats-server-$NATS_VERSION-linux-amd64.zip" -O tmp.zip
          unzip tmp.zip
          mv nats-server-$NATS_VERSION-linux-amd64 nats-server

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: stable
          check-latest: true

      - name: Install deps
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Lint
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          go build
          if [ "$(go fmt ./... | wc -l)" -gt 0 ]; then
            echo "gofmt failed; to fix, run: 'go fmt ./...'"
            exit 1
          fi
          go vet ./...
          $HOME/go/bin/staticcheck ./...

      - name: Run tests
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          # go test -vet=off -v -run=TestNoRace --failfast -p=1 ./...
          # coverage via cov.sh disabled while just testing the waters
          # Also disable race since we are overwhelming the GHA runners.
          go test -vet=off -v -p=1 --failfast ./...
